# src/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pbdkn\ContaoBesslichschmuck\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Resources/contao,dca,Resources/public}'

    Pbdkn\ContaoBesslichschmuck\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    # Registrierung des CgiUtil-Dienstes
    Pbdkn.ContaoBesslichschmuck.util.cgi_util:
        class: Pbdkn\ContaoBesslichschmuck\Util\CgiUtil

    # Registrierung von BesslichUtil mit seinen Abhängigkeiten
    Pbdkn.ContaoBesslichschmuck.util.besslich_util:
        class: Pbdkn\ContaoBesslichschmuck\Util\BesslichUtil
        arguments:
            $connection: '@database_connection'       # Die Doctrine DBAL-Verbindung
            $cgiUtil: '@Pbdkn.ContaoBesslichschmuck.util.cgi_util'  # Der CgiUtil-Dienst
            
    Pbdkn\ContaoBesslichschmuck\Controller\DetailArtikelDisplayController:
        public: true
        autowire: false
        autoconfigure: false
        tags:
            - { name: contao.frontend_module category:"besslich_schmuck"}


      