# src/Resources/config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pbdkn\ContaoBesslichschmuck\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Resources/contao,dca,Resources/public}'

    Pbdkn\ContaoBesslichschmuck\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
   
#    contao.picker.file_provider:
#        class: Contao\CoreBundle\Picker\FilePickerProvider
#        public: true
#        arguments: ['@service_container']
#        tags:
#            - { name: 'contao.picker.provider', context: 'file' }


            

      